.TH RT_TBX_DELETE 8 "January 2001" RTAI "Typed Mailbox Functions"
.SH NAME
rt_tbx_delete \- delete a typed mailbox
.SH SYNOPSIS
.B #include <rtai_sched.h>
.sp
.BI "int rt_tbx_delete(TBX " *tbx ");"
.SH DESCRIPTION
.B rt_tbx_delete
removes a typed mailbox previously created with
.B rt_tbx_init(8).
.I tbx 
points to the structure used in the corresponding call to 
.B rt_tbx_init(8).
.SH RETURN VALUES
On success 0 is returned. On failure a negative value is returned as described below. 
.SH ERRORS 
.B -EINVAL
.I tbx
points to an invalid mailbox.
.br
.B -EFAULT
.I tbx
data was found in an invalid state.
