.TH RT_TBX_URGENT_TIMED 8 "January 2001" RTAI "Typed Mailbox Functions"
.SH NAME
rt_tbx_urgent_until, rt_tbx_urgent_timed \- send message unconditionally with high priority 
and timeout control
.SH SYNOPSIS
.B #include <rtai_sched.h>
.sp
.BI "int rt_tbx_urgent_until(TBX " *tbx ", void " *msg ", int " msg_size ", RTIME " time ");"
.br
.BI "int rt_tbx_urgent_timed(TBX " *tbx ", void " *msg ", int " msg_size ", RTIME " delay ");"
.SH DESCRIPTION
.B rt_tbx_urgent_until 
and 
.B rt_tbx_urgent_timed 
send a message 
.I msg 
of 
.I msg_size 
bytes to the typed mailbox 
.I tbx. 
The caller will be blocked until all
bytes of message is inserted, the timeout expires or an error occurs. 
The message is inserted in the head of the queue 
so it will be immediately read before the other messages already
present in the mailbox.
.I time 
is an absolute value. 
.I delay 
is relative to the current time.
.SH RETURN VALUES
0 is returned in case of message regularly sent, otherwise 
.I msg_size
is returned in case of timeout. On failure a negative value is returned as described below.
.SH ERRORS
.B -EINVAL
.I tbx
points to an invalid typed mailbox.
.B -EMSGSIZE
.I msg_size
is bigger than the size of the entire mailbox.

