.TH RT_TBX_RECEIVE_IF 8 "January 2001" RTAI "Typed Mailbox Functions"
.SH NAME
rt_tbx_receive_if \- receive a message if available
.SH SYNOPSIS
.B #include <rtai_sched.h>
.sp
.BI "int rt_tbx_receive_if(TBX " *tbx ", void " *msg ", int " msg_size ");"
.SH DESCRIPTION
.B rt_tbx_receive_if 
receives a message from the typed mailbox 
.I tbx 
if the whole message of 
.I msg_size 
bytes is available immediately. 
.I msg 
points to a buffer provided by the caller.
.SH RETURN VALUES
0 is returned in case of message regularly received, otherwise 
.I msg_size
is returned. On failure a negative value is returned as described below.
.SH ERRORS
.B -EINVAL
.I tbx
points to an invalid typed mailbox.
.B -EMSGSIZE
.I msg_size
is bigger than the size of the entire mailbox.

