#!/bin/sh

cat <<-EOF

This is a simple test to verify that a fast high priority task
preempts a long lasting lower priority one.

Type <return> to install the modules
EOF

read junk
sync

../../scripts/rt_modprobe ex_preempt.o

echo "Now start the application"
echo "To stop the application type Ctrl-C"
echo "Type <return> to continue"
read junk
./check

echo " "
echo "Type <return> to remove modules"
read junk
sync

../../scripts/rt_rmmod ex_preempt

