#!/bin/sh

cat <<-EOF
This example demonstrates the use of named objects.  Its output
is to the console, so running it in a normal xterm isn't very
interesting.

Type <return> to continue
EOF
read junk

../../scripts/rt_modprobe ../../modules/rtai_sched_ext.o
../../scripts/rt_modprobe ex_named.o

echo "Wait for its end (msg: task 3 complete), then type <return> to remove modules"
read junk
sync
../../scripts/rt_rmmod ex_named
# ../../scripts/rt_rmmod rtai_sched_ext
