#!/bin/sh

if [ $UID = 0 ]; then
	CHECK='./check'
else
	CHECK='sudo ./check'
fi

cat <<-EOF

This test shows how you can use the RTAI module to install an
interrupt handler to simulate a higher tick communicating with
it through a fifo.

Type <return> to install modules.
EOF
read junk

../../scripts/rt_modprobe ex_fastick_2.o

echo "Now start the application"
echo "To stop the application type Ctrl-C"
echo "Type <return> to continue"
read junk

$CHECK

echo " "
echo "Type <return> to remove modules"
read junk

../../scripts/rt_rmmod ex_fastick_2

