#!/bin/sh

sync
insmod ../../modules/rtai.o
insmod ../../modules/rtai_sched.o
insmod ../../modules/rtai_lxrt.o
insmod ./sysAuxClk.o
insmod ./rtc.o
sync
./check
sync
rmmod rtc
rmmod sysAuxClk
rmmod rtai_lxrt
rmmod rtai_sched
rmmod rtai
