#!/bin/sh

cat <<-EOF
This tests runs two real time tasks that send data down a fifo
to a Linux application that prints the data on the terminal.
One task outputs the data "Frank".  The other task outputs the
data "Zappa".  This test is due to Michael Barabanov: a fan of
the late composer.

Type <return> to continue"
EOF
read junk

../../scripts/rt_modprobe ex_frank.o

echo "Now start the application"
echo "Type <return> to continue"
read junk
./frank_app

../../scripts/rt_rmmod ex_frank


