#!/bin/sh

cat <<-EOF

This example demonstrates the use of RTAI mailboxes.  It has two
senders and one receiver that exchange messages on mailboxes.
Just run it for some time, if nothing appears on the screen then
it is OK.  See the code to understand why.

Type <return> to continue
EOF
read junk

sync
../../scripts/rt_modprobe ex_mbx.o

echo "Program is running"
echo "Type <return> to remove modules"
read junk

sync
../../scripts/rt_rmmod ex_mbx

echo "Type <return> to leave this test"
read junk
